version: "1"

volumes:
  mongodb_volume:

services:
  build: .
  restart: always
  environment:
    - MONGO_DB_ADDR=mongodb
    - MONGO_DB_PORT=27017

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always